---
include:
  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_corne_central_dongle_oled
  - board: eyelash_corne_right
    shield: nice_view_custom
  - board: eyelash_corne_left
    shield: nice_view_custom
  - board: nice_nano_v2
    shield: settings_reset 
