---
include:
  - board: nice_nano_v2
    shield: corne_dongle dongle_display
  - board: eyelash_corne_left
    shield: nice_view_custom
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: eyelash_corne_right
    shield: nice_view_custom
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # - board: eyelash_corne_left
  #   shield: nice_view
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #   artifact-name: eyelash_corne_studio_left
  # - board: eyelash_corne_right
  #   shield: nice_view
  - board: nice_nano_v2
    shield: settings_reset 
